services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: redal-formosa:latest
    container_name: redal-formosa
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - path: .env.local
        required: false
